// -*- mode: c++ -*-

/***** Auto generated file: DO NOT EDIT !!!!!! *****/
/*** Generated at: Tue 23 May-2023 04:21:16  ***/
/*** Generated from config\logging.xml **/
/*** Validated by config\logging.xsd **/

/****************************************************************************
*** Copyright(C) 2023  Per Thomas Hille, pth@embc.no                  ***
*** This file is part of logmaster.logmaster is free software : you can   ***
*** redistribute it and / or modify it under the terms of the Lesser GNU  ***
*** General Public License(LGPL) V3 or later. See.cpp file for details    ***
*****************************************************************************/


#pragma once

#include <testlib/TestBase.h>

class TestHashMapsAutoGenerated : public TestBase
{
public:
    TestHashMapsAutoGenerated( ) = default;
    virtual  ~TestHashMapsAutoGenerated( ) = default;
};

