// -*- mode: c++ -*-

/***** Auto generated file: DO NOT EDIT !!!!!! *****/
/*** Generated at: Fri 27 October-2023 22:53:13  ***/
/*** Generated from config/logging.xml **/
/*** Validated by config/logging.xsd **/

/****************************************************************************
*** Copyright(C) 2023  Per Thomas Hille, pth@embc.no                  ***
*** This file is part of logmaster.logmaster is free software : you can   ***
*** redistribute it and / or modify it under the terms of the Lesser GNU  ***
*** General Public License(LGPL) V3 or later. See.cpp file for details    ***
*****************************************************************************/


#pragma once

#include <testlib/TestBase.h>

class TestLConversionAutoGenerated : public TestBase
{
public:
    TestLConversionAutoGenerated( ) = default;
    virtual  ~TestLConversionAutoGenerated( ) = default;
};

