// -*- mode: c++ -*-

/***** Auto generated file: DO NOT EDIT !!!!!! *****/
/*** Generated at: Tue 23 May-2023 04:21:16  ***/
/*** Generated from config\logging.xml **/
/*** Validated by config\logging.xsd **/

/***************************************************
* @copyright Embedded Consulting AS    2023        *
* @author Per Thomas Hille <pth@embc.no>           *
***************************************************/

/********************************************************************************
*********************************************************************************
*** This file is part of logmaster.                                           ***
*** Copyright (C) 2023 Per Thomas Hille <pth@embc.no>  http:///www.embc.no    ***
*** all rights reserved                                                       ***
***                                                                           ***
*** logmaster is free software: you can redistribute it and/or modify         ***
*** it under the terms of the Lesser GNU General Public License (LGPL)        ***
*** as published by the Free Software Foundation, either version 3 of the     ***
*** License, or (at your option) any later version.                           ***
***                                                                           ***
*** logmaster is distributed in the hope that it will be useful,              ***
*** but WITHOUT ANY WARRANTY; without even the implied warranty of            ***
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             ***
*** GNU General Public License for more details.                              ***
***                                                                           ***
*** You should have received a copy of the Lesser GNU General Public          ***
*** License along with logmaster in the README file in the source code        ***
*** directory. If not, see <http://www.gnu.org/licenses/>.                    ***
*********************************************************************************
*********************************************************************************/

#include "TestLHashMaps.h"
#include "TestHashMapsAutoGenerated.h"
#include <utilities/GUtilities.h>
#include <logging/LHashMaps.h>
using namespace LOGMASTER;
#include <vector>
using std::vector;




TEST_F(TestHashMapsAutoGenerated, IsSubCmdhash)
{
    vector<eMSGSYSTEM>  systems = LHashMaps::GetSystemEnums();
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_EXCEPTION));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_FSM));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_MESSAGE));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_COM));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_XML));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_DATABASE));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_USER));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_GENERAL));
    EXPECT_TRUE(g_utilities()->Contains(systems,eMSGSYSTEM::SYS_ALARM));
}



