// -*- mode: c++ -*-

/***** Auto generated file: DO NOT EDIT !!!!!! *****/
/*** Generated at: Fri 16 August-2024 18:59:12  ***/
/*** Generated from config/logging-ucw.xml **/
/*** Validated by config/logging.xsd **/

/****************************************************************************
*** Copyright(C) 2024  Per Thomas Hille, pth@embc.no                  ***
*** This file is part of logmaster.logmaster is free software : you can   ***
*** redistribute it and / or modify it under the terms of the Lesser GNU  ***
*** General Public License(LGPL) V3 or later. See.cpp file for details    ***
*****************************************************************************/


#pragma once

#include <testlib/TestBase.h>

class TestLConversionAutoGenerated : public TestBase
{
public:
    TestLConversionAutoGenerated( ) = default;
    virtual  ~TestLConversionAutoGenerated( ) = default;
};

