// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/


#include <string>
using std::string; 

#include <version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v0.0.0-2-g98e97e7";
const string GVersion::fCompileFlags = "c++ -std=c++17 -fPIC -std=c++17 -ggdb -o gui-habitat-example1 gui-habitat-example1.o -L /home/perthi/nautilus/software/build/x86/lib -lm -lhabitat -lintercom -lcommon -lgui-common -lapi-hmi -lcom -lprotocol -lconfiguration -lkf-commands -lcom -lkf-com -lkf-commands -lxml-embc -lxml2 -lcmdline -llogmaster -lutilities -lreadline -lboost_system -lboost_filesystem -lQt5Charts -lpthread -L /home/perthi/nautilus/software/3rd-party/protobuf/lib -lprotobuf -L /home/perthi/Qt/5.15.0//gcc_64/lib -lQt5Widgets -lQt5Core -lQt5Gui";
const string GVersion::fLinkFlags = "-L /home/perthi/nautilus/software/build/x86/lib -lm -lhabitat -lintercom -lcommon -lgui-common -lapi-hmi -lcom -lprotocol -lconfiguration -lkf-commands -lcom -lkf-com -lkf-commands -lxml-embc -lxml2 -lcmdline -llogmaster -lutilities -lreadline -lboost_system -lboost_filesystem -lQt5Charts -lpthread -L /home/perthi/nautilus/software/3rd-party/protobuf/lib -lprotobuf -L /home/perthi/Qt/5.15.0//gcc_64/lib -lQt5Widgets -lQt5Core -lQt5Gui";
string GVersion::fOriginalExeName = "unknowne_exefile";
const string GVersion::fGitInfo = "Repository Path: /home/perthi/nautilus/.git\n\
Path: /home/perthi/nautilus/software/gui/habitat/examples/gui-habitat-example1/x86\n\
Remote Repositories:\n\
	origin	git_github.com:perthi/nautilus.git (fetch)\n\
	origin	git_github.com:perthi/nautilus.git (push)\n\
Remote Branches:\n\
	origin/HEAD -> origin/master\n\
	origin/master\n\
Local Branches:\n\
	_ master\n\
Repository Configuration:\n\
	[branch master]\n\
		merge = refs/heads/master\n\
		remote = origin\n\
	[core]\n\
		bare = false\n\
		filemode = true\n\
		logallrefupdates = true\n\
		repositoryformatversion = 0\n\
	[remote origin]\n\
		fetch = +refs/heads/_:refs/remotes/origin/_\n\
		url = git_github.com:perthi/nautilus.git\n\
Last Changed Commit ID: b444ed29cbd28bfee0dcf4ad8845c951cbcc132c\n\
Last Changed Author: Per Thomas <pth_embc.no>\n\
Last Changed Date: Wed Aug 26 18:33:10 2020 +0200\n\
Last Changed Log:\n\
	initial commit\n\
";


