// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/
/******		Date: [Tue 09 May-2023 21:37:29]		*****/




#include <string>
using std::string; 

#include <utilities/version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v1-2-1-ucw-143-g91e64aa";
const string GVersion::fCompileFlags = "c++ -std=c++17 -fPIC -std=c++17 -g -DGUI_DIR=\"/home/perthi/work/logmaster\" -ggdb -Weffc++ -Wshadow -Wall -Wextra -Wpedantic -Wno-psabi -Wno-unknown-pragmas -Wswitch-enum -Wimplicit-fallthrough -Wignored-qualifiers -Wno-format-security -DHAS_LOGGING";
const string GVersion::fLinkFlags = "-L /home/perthi/work/logmaster/build/x86/lib -lm -lconfigurator -lxml-embc -lxml2 -lcmdline -llogmaster -lutilities -lpthread -lreadline -lsqlite-embc -ldl -lpthread";
const string GVersion::fOriginalExeName = "logging-configurator";
const string GVersion::fGitInfo = "__ Remote URLs:\n\
origin	git_github.com:perthi/logmaster.git (fetch)\n\
origin	git_github.com:perthi/logmaster.git (push)\n\
__ Remote Branches:\n\
  origin/HEAD -> origin/master\n\
  origin/master\n\
  origin/v1-1-release\n\
  origin/v1-2-release-fist\n\
__ Local Branches:\n\
_ master\n\
__ Most Recent Commit:\n\
commit 91e64aa96a8e2a52d3336d395595c6c076bc1c81\n\
Author: perthi <pth_embc.no>\n\
    Compilation for linux\n\
Type 'git log' for more commits, or 'git show <commit id>' for full commit details.\n\
__ Configuration (.git/config):\n\
user.name=perthi\n\
user.email=pth_embc.no\n\
core.repositoryformatversion=0\n\
core.filemode=true\n\
core.bare=false\n\
core.logallrefupdates=true\n\
remote.origin.url=git_github.com:perthi/logmaster.git\n\
remote.origin.fetch=+refs/heads/_:refs/remotes/origin/_\n\
branch.master.remote=origin\n\
branch.master.merge=refs/heads/master\n\
";


