// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/
/******		Date: [Wed 10 May-2023 16:05:22]		*****/




#include <string>
using std::string; 

#include <utilities/version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v1-2-1-ucw-144-gac24775";
const string GVersion::fCompileFlags = "";
const string GVersion::fLinkFlags = "-L /home/perthi/work/logmaster/build/x86/lib -lm -lcmdline -llogmaster -lutilities -llogmaster -lcmdline -lsqlite-embc -lreadline -lhistory -lncurses -ldl -lpthread -lreadline";
const string GVersion::fOriginalExeName = "helloworld";
const string GVersion::fGitInfo = "__ Remote URLs:\n\
origin	git_github.com:perthi/logmaster.git (fetch)\n\
origin	git_github.com:perthi/logmaster.git (push)\n\
__ Remote Branches:\n\
  origin/HEAD -> origin/master\n\
  origin/master\n\
  origin/v1-1-release\n\
  origin/v1-2-release-fist\n\
__ Local Branches:\n\
_ master\n\
__ Most Recent Commit:\n\
commit ac24775309f1b0a3f243797d398f80d254c02a93\n\
Author: perthi <pth_embc.no>\n\
    compilation for Linux\n\
Type 'git log' for more commits, or 'git show <commit id>' for full commit details.\n\
__ Configuration (.git/config):\n\
user.name=perthi\n\
user.email=pth_embc.no\n\
core.repositoryformatversion=0\n\
core.filemode=true\n\
core.bare=false\n\
core.logallrefupdates=true\n\
remote.origin.url=git_github.com:perthi/logmaster.git\n\
remote.origin.fetch=+refs/heads/_:refs/remotes/origin/_\n\
branch.master.remote=origin\n\
branch.master.merge=refs/heads/master\n\
";


