// -*- mode: c++ -*-


#include <configurator/LXmlParser.h>
#include  <xml-parser/xml/GXmlValidator.h>
//#include <logging/LLogApi.h>
#include <configurator/LXmlEntityLogLevel.h>
#include <configurator/LXmlEntitySubSystem.h>
//#include <configurator/LCreateDefaultGenerators.h>
#include <configurator/LGeneratorLoggingSystemTests.h>
#include <configurator/LFileCreator.h>
#include <configurator/LArgumentScanner.h>
//#include <configurator/LDefinitions.h>
#include <configurator/LXMLInfo.h>
#include <utilities/version-info/GMenu.h>

#include <logging/LLogApi.h>
#include <logging/LPublisher.h>
#include <utilities/version-info/GMenu.h>
#include <utilities/GFileIOHandler.h>
#include <cmdline/GCommandLineArgument.h>
#include <cmdline/GArgument.h>
#include <utilities/GFileIOHandler.h>
#include <utilities/GSystem.h>
#include <logging/GException.h>
#include <logging/LConversion.h>

using namespace LOGMASTER;


#ifdef _W_IN32
#include <Windows.h>
#endif


#include <stdio.h>
#include <thread>
#include <chrono>
#include <optional>
#include <string>
#include <filesystem>

#include <utilities/GRandom.h>

#include <configurator/LFileCreator.h>


#include <string>
using std::string;


using namespace LOGMASTER;
using namespace CONFIGURATOR;

#include <format>


#include <format>

int main(int  argc, const char** argv)
{
    string test= "foo bar";
    //FORCE_DEBUG(test);

    int t = 12345;
    // string test2;
    
    for (int i = 0; i < 100; i++)
    {
        t++;
     //   test2 = std::format("TESTING STD FORMAT {:#x}", t);
        FORCE_DEBUG(  std::format("TESTING STD FORMAT {:#x}", t)  );
    
    }


   ////  FORCE_DEBUG(test2);

   // FORCE_DEBUG(std::format("TESTING STD FORMAT {:x#}", 12345)) ;

    return 0;
   // long long int num = 0x123456789;
   /// cout << std::format(f, num);
   /// std::format fmt;
    //cout << std::format("{:#03x}\n"), num);

    cout << g_random( )->Uniform<int>(0, 10000) << endl;
   
   // return 0;
   
    //LConversion::String2System("000000110000000000000100");

    GMenu::Instance( )->ScanArguments(argc, argv);

    SET_LOGLEVEL("--all-off --all-warning");
    SET_LOGFORMAT("1111111");

  


    try
    {
        string xml = "";
        string xsd = "";

        LArgumentScanner::ScanArguments(argc, argv, xml, xsd);

        XML_ASSERT_EXCEPTION(GXmlValidator( ).IsValid(xml, xsd), "failed to validate %s against %s", xml.c_str( ), xsd.c_str( ));
        logentity_vec  loglevels;
        sysentity_vec  subsystems;
        LXmlParser( ).ParseXML(xml, xsd, loglevels, subsystems);
        XML_INFO("Successfully validated %s against %s and parsed the XML file", xml.c_str( ), xsd.c_str( ));
        auto l_system =  std::make_shared<LGeneratorLoggingSystemTests>("logging/unit-tests/commit/", "TestLConversionAutoGenerated", (LXMLInfo(xml, xsd)));

        LFileCreator( ).GenerateSingleFile(l_system, loglevels, subsystems);

    }
    catch ( const GException& e )
    {
        std::cerr << e.what( ) << endl;
    }
    catch ( const std::exception& e )
    {
        std::cerr << e.what( ) << endl;
    }
    catch ( const std::string& e )
    {
        std::cerr << e << endl;
    }
    catch ( ... )
    {
        FORCE_DEBUG("Unknown exception caught ....");
    }

    //   std::this_thread::sleep_for(std::chrono::milliseconds(10));

}

