// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/


#include <string>
using std::string; 

#include <version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v0.0.0-2-g98e97e7";
const string GVersion::fCompileFlags = "c++ -std=c++17 -fPIC -std=c++17 -ggdb -o gui-main gui-main.o GUIMainWindow.o GUIMainWindow_moc.o GUIResources.o -L /home/perthi/nautilus/software/build/x86/lib -lm -lcmdline -llogmaster -lutilities -lreadline -lpthread -lgui-logger -lgui-logmaster -lapi-logmaster -lgui-common -lgui-fsm -lgui-settings -lgui-alarm -lkf-main -lapi-fsm -lcommon -lcmdline -llogmaster -lxml-embc -lxml2 -lgui-common -lgui-sensors -lapi-sensors -lcontrol-engine -lapi-hmi -lintercom -lcom -lprotocol -lutilities -lreadline -lboost_system -lboost_filesystem -lconfiguration -lc-ring -lgui-operations -lsequence -lQt5Charts -lintercom -lkf-com -lcom -lkf-commands -lapi-hmi -lQt5Quick -lQt5Qml -lQt5QuickWidgets -lprotocol -L /home/perthi/Qt/5.15.0//gcc_64/lib -lQt5Widgets -lQt5Core -lQt5Gui -L /home/perthi/Qt/5.15.0//gcc_64/lib";
const string GVersion::fLinkFlags = "-L /home/perthi/nautilus/software/build/x86/lib -lm -lcmdline -llogmaster -lutilities -lreadline -lpthread -lgui-logger -lgui-logmaster -lapi-logmaster -lgui-common -lgui-fsm -lgui-settings -lgui-alarm -lkf-main -lapi-fsm -lcommon -lcmdline -llogmaster -lxml-embc -lxml2 -lgui-common -lgui-sensors -lapi-sensors -lcontrol-engine -lapi-hmi -lintercom -lcom -lprotocol -lutilities -lreadline -lboost_system -lboost_filesystem -lconfiguration -lc-ring -lgui-operations -lsequence -lQt5Charts -lintercom -lkf-com -lcom -lkf-commands -lapi-hmi -lQt5Quick -lQt5Qml -lQt5QuickWidgets -lprotocol -L /home/perthi/Qt/5.15.0//gcc_64/lib -lQt5Widgets -lQt5Core -lQt5Gui -L /home/perthi/Qt/5.15.0//gcc_64/lib";
string GVersion::fOriginalExeName = "unknowne_exefile";
const string GVersion::fGitInfo = "Repository Path: /home/perthi/nautilus/.git\n\
Path: /home/perthi/nautilus/software/gui/application/main/x86\n\
Remote Repositories:\n\
	origin	git_github.com:perthi/nautilus.git (fetch)\n\
	origin	git_github.com:perthi/nautilus.git (push)\n\
Remote Branches:\n\
	origin/HEAD -> origin/master\n\
	origin/master\n\
Local Branches:\n\
	_ master\n\
Repository Configuration:\n\
	[branch master]\n\
		merge = refs/heads/master\n\
		remote = origin\n\
	[core]\n\
		bare = false\n\
		filemode = true\n\
		logallrefupdates = true\n\
		repositoryformatversion = 0\n\
	[remote origin]\n\
		fetch = +refs/heads/_:refs/remotes/origin/_\n\
		url = git_github.com:perthi/nautilus.git\n\
Last Changed Commit ID: b444ed29cbd28bfee0dcf4ad8845c951cbcc132c\n\
Last Changed Author: Per Thomas <pth_embc.no>\n\
Last Changed Date: Wed Aug 26 18:33:10 2020 +0200\n\
Last Changed Log:\n\
	initial commit\n\
";


